if &shell =~# 'fish$'
  set shell=sh
endif

autocmd FileType fish compiler fish
autocmd FileType fish setlocal textwidth=79
filetype off

so ~/.vim/plugs.vim

set t_Co=256
" set spell " Sets the spellchecker. Not so great when coding
set clipboard=unnamed

" Set the directories for the swp and un files
set noswapfile
set backupdir=~/.vim/backup
set undodir=~/.vim/undo

let mapleader=","
imap jj <Esc>

function! EscapeAndSafe()
  exec ":w"
endfunction

command! EscNSafe call EscapeAndSafe()
nnoremap <leader>w :EscNSafe<cr>
map <leader>, :execute ":b#"<cr>
map <leader>a :execute ":A"<cr>

syntax enable
let base16colorspace=256
set background=dark
colorscheme base16-default

set encoding=utf8

" Indentation and tabs
syntax on
filetype plugin indent on
set tabstop=2
set autoindent
set expandtab

set scrolloff=3
set shiftwidth=2

set showcmd
set ruler
set title
set number
set shortmess=atI
set visualbell
set laststatus=2
set cmdheight=1

set showtabline=2
set guioptions-=e

" Airline
let g:airline#extensions#tabline#enabled=1
let g:airline#extensions#tabline#left_sep=' '
let g:airline#extensions#tabline#left_alt_sep='|'
let g:airline_powerline_fonts=1
let g:airline_theme='base16-default'

set wrap
set textwidth=79
set formatoptions=qrn1
set colorcolumn=78

set cursorline
:hi CursorLine cterm=NONE ctermbg=darkgrey ctermfg=white guibg=darkgrey guifg=white

:hi TabLineSel ctermfg=white ctermbg=blue
:hi TabLine ctermfg=white ctermbg=darkgrey

set numberwidth=4
set backspace=indent,eol,start

set incsearch
set undofile

nnoremap ' `
nnoremap ` '
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
nnoremap <Tab> <C-w><C-w>

set listchars=tab:>-,trail:·,eol:$
nmap <silent> <leader>s :set nolist!<CR>
nmap <silent> <leader>srn :set relativenumber<CR>
nmap <silent> <leader>snn :set number<CR>

" NERDTree mappings
map <leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>

au BufNewFile,BufRead *.ejs set filetype=html
au BufNewFile,BufRead *.md set filetype=markdown

let g:markdown_fenced_languages = ['html', 'python', 'bash=sh']

" CRLTP
map <leader>b :CtrlPBuffer<CR>
map <leader>f :CtrlPCurFile<CR>
let g:ctrlp_map='<leader>t'
let g:ctrlp_working_path_mode=0
set wildignore+=*/tmp/*,*.so,*.swp,*.un*,.git,*.zip,.DS_Store,.jhw-cache/*  " MacOSX/Linux
let g:ctrlp_custom_ignore='\.git$|\.svn$|\.swp$|\.o$|\.un\˜$|\.DS_Store$|\.jhw-cache$'
let g:tablabel ="%N%{flagship#tabmodified()} %{flagship#tabcwds('shorten',',')}"

" Unbinding the arrow keys
set ofu=syntaxcomplete#Complete
for prefix in ['i', 'n', 'v']
  for key in ['<Up>', '<Down>', '<Left>', '<Right>']
    exe prefix . "noremap " . key . " <Nop>"
  endfor
endfor
